"""remove fingerprint columns

Revision ID: 0415bd61311d
Revises: 07a4944981ea
Create Date: 2024-10-07 13:39:51.756410

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0415bd61311d'
down_revision = '07a4944981ea'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('polymers', 'fingerprint')
    op.drop_column('solvents', 'fingerprint')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('solvents', sa.Column('fingerprint', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('polymers', sa.Column('fingerprint', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
