"""upgrade_primary_key_of_processed

Revision ID: 07a4944981ea
Revises: 9627872f87bb
Create Date: 2024-03-02 16:18:34.438714

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07a4944981ea'
down_revision = '9627872f87bb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "csst_reactor_processed_temperature_values_pkey",
        "csst_reactor_processed_temperature_values",
    )
    op.create_primary_key(
        "csst_reactor_processed_temperature_values_pkey",
        "csst_reactor_processed_temperature_values",
        [
            "csst_reactor_id",
            "average_temperature",
            "temperature_range",
            "heating",
            "cooling",
            "holding",
            "filtered"
        ],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "csst_reactor_processed_temperature_values_pkey",
        "csst_reactor_processed_temperature_values",
    )
    op.create_primary_key(
        "csst_reactor_processed_temperature_values_pkey",
        "csst_reactor_processed_temperature_values",
        [
            "csst_reactor_id",
            "average_temperature",
            "temperature_range",
            "heating",
            "cooling",
            "holding",
        ],
    )
    # ### end Alembic commands ###
