"""add ramp states to processed temperature values

Revision ID: 81bc11bf15e2
Revises: f989125d2d74
Create Date: 2024-02-29 13:55:11.374541

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "81bc11bf15e2"
down_revision = "f989125d2d74"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "csst_reactor_processed_temperature_values",
        sa.Column("heating", sa.Integer(), nullable=False),
    )
    op.add_column(
        "csst_reactor_processed_temperature_values",
        sa.Column("cooling", sa.Integer(), nullable=False),
    )
    op.add_column(
        "csst_reactor_processed_temperature_values",
        sa.Column("holding", sa.Integer(), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("csst_reactor_processed_temperature_values", "holding")
    op.drop_column("csst_reactor_processed_temperature_values", "cooling")
    op.drop_column("csst_reactor_processed_temperature_values", "heating")
    # ### end Alembic commands ###
