"""add filtered column to processed data

Revision ID: 9627872f87bb
Revises: 621a4847fe0c
Create Date: 2024-03-02 16:16:12.275135

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9627872f87bb'
down_revision = '621a4847fe0c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('csst_reactor_processed_temperature_values', sa.Column('filtered', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('csst_reactor_processed_temperature_values', 'filtered')
    # ### end Alembic commands ###
